require 'gmr.core.options'
require 'gmr.core.keymaps'
require 'gmr.core.autocmds'
require 'gmr.core.commands'
require 'gmr.core.statusline'
require 'gmr.core.winbar'
require 'gmr.core.terminalcolors'
require 'gmr.lazy'
-- require 'gmr.configs.base46'
