-- improve startup time
require("impatient")
require("filetype").setup({})

-- options and configs
require("config.options")
require("config.keymaps")
require("config.plugins")
require("config.colorschemes.catppuccin")
require("config.cmp")
require("config.lsp")
require("config.trouble")
require("config.telescope")
require("config.treesitter")
require("config.autopairs")
require("config.kommentary")
require("config.gitsigns")
require("config.nvim-tree")
require("config.bufferline")
require("config.toggleterm")
require("config.formatter")
require("config.colorizer")
require("config.indent-blankline")
require("config.cmds")
