require("nvim-treesitter.configs").setup {
    ensure_installed = "maintained",
	ignore_install = {
		"bash",
		"beancount",
		"bibtex",
		"clojure",
		"cmake",
		"comment",
		"commonlisp",
		"css",
		"cuda",
		"dart",
		"devicetree",
		"dockerfile",
		"elixir",
		"elm",
		"erlang",
		"fennel",
		"fish",
		"fortran",
		"haskell",
		"html",
		"hcl",
		"julia",
		"kotlin",
		"latex",
		"ledger",
		"nix",
		"ocaml",
		"ocaml_interface",
		"ocamllex",
		"php",
		"ql",
		"r",
		"ruby",
		"scala",
		"sparql",
		"supercollider",
		"svelte",
		"swift",
		"teal",
		"turtle",
		"verilog",
		"vue",
		"zig"
	},
    highlight = {enable = true},
    rainbow = {enable = true, extended_mode = true, max_file_lines = 1000}
}
