local M = {}

M.to_setup = {
    'angularls',
    'astro',
    'bashls',
    'biome',
    'buf_ls',
    'clangd',
    'cssls',
    'denols',
    'dockerls',
    'elixirls',
    -- 'emmet_ls',
    'emmet_language_server',
    'eslint',
    'gleam',
    'gopls',
    'html',
    'intelephense',
    -- 'jdtls',
    'jsonls',
    -- 'kotlin_language_server',
    'nim_langserver',
    'nushell',
    'ocamllsp',
    'omnisharp',
    'postgres_lsp',
    -- 'pylance',
    -- 'pylyzer',
    -- 'phpactor',
    'pyright',
    'ruff',
    'rust_analyzer',
    'templ',
    -- "solargraph",
    'svelte',
    'lua_ls',
    'tailwindcss',
    'taplo',
    'ts_ls',
    'vimls',
    'volar',
    -- 'vtsls',
    'yamlls',
    -- 'zls',
}

return M
