local M = {}

M.to_setup = {
    -- 'angularls',
    'astro',
    'bashls',
    -- 'biome',
    'buf_ls',
    'clangd',
    'cssls',
    'denols',
    'dockerls',
    'elixirls',
    -- 'eslint',
    'gopls',
    'html',
    'intelephense',
    -- 'jdtls',
    'jsonls',
    -- 'kotlin_language_server',
    'kotlin_lsp',
    'nushell',
    -- 'ocamllsp',
    'omnisharp',
    'ols',
    'postgres_lsp',
    -- 'pylance',
    -- 'pylyzer',
    -- 'phpactor',
    'pyright',
    'ruff',
    'rust_analyzer',
    'templ',
    'svelte',
    'lua_ls',
    'tailwindcss',
    'taplo',
    'tsgo',
    -- 'ts_ls',
    -- 'vtsls',
    'yamlls',
    -- 'zls',
}

return M
